language: ruby

rvm:
  - 2.5.1

script:
  - cd katas
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec .
  # - bundle exec rubocop

notifications:
  email:
    recipients:
      - ategdroid@gmail.com
    on_failure: always # default: always
    on_success: change # default: change
    #on_start: change  